/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class breeze_pvz_cheater_utils_PVZHooker */

#ifndef _Included_breeze_pvz_cheater_utils_PVZHooker
#define _Included_breeze_pvz_cheater_utils_PVZHooker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    isRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_isRunning
  (JNIEnv *, jclass);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    infinitSunshine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_infinitSunshine
  (JNIEnv *, jclass, jint);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    infinitCoin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_infinitCoin
  (JNIEnv *, jclass, jint);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    alterFertilizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_alterFertilizer
  (JNIEnv *, jclass, jint);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    alterTreeFertilizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_alterTreeFertilizer
  (JNIEnv *, jclass, jint);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    alterTreeHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_alterTreeHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    alterherbicide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_alterherbicide
  (JNIEnv *, jclass, jint);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    clearCD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_clearCD
  (JNIEnv *, jclass);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    alterChocolate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_alterChocolate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
