/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class breeze_pvz_cheater_utils_PVZHooker */

#ifndef _Included_breeze_pvz_cheater_utils_PVZHooker
#define _Included_breeze_pvz_cheater_utils_PVZHooker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    isRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_isRunning
  (JNIEnv *, jclass);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    infinitSunshine
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_infinitSunshine
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     breeze_pvz_cheater_utils_PVZHooker
 * Method:    infinitCoin
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_breeze_pvz_cheater_utils_PVZHooker_infinitCoin
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
